services:
  postgres:
    container_name: wochterbuch-postgres
    image: postgres:alpine3.17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - wochterbuch-postgres:/var/lib/postgresql/data
    networks:
      - wochterbuch-internal

  backend:
    container_name: wochterbuch-backend
    build:
      context: ../wochterbuch-backend
      dockerfile: Dockerfile
    env_file:
      - backend.local.env
    ports:
      - "6029:6029"
    depends_on:
      - postgres
    networks:
      - wochterbuch-internal


volumes:
  wochterbuch-postgres:

networks:
  wochterbuch-internal:
    driver: bridge
