name: wochterbuch

services:
  postgres:
    container_name: wochterbuch-postgres
    image: postgres:alpine3.17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 1s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - wochterbuch-postgres:/var/lib/postgresql/data
    networks:
      - wochterbuch-internal

  backend:
    container_name: wochterbuch-backend
    build:
      context: ../wochterbuch-backend
      dockerfile: Dockerfile
    env_file:
      - backend.local.env
    ports:
      - "6029:6029"
    volumes:
      - ../wochterbuch-backend/dict:/app/dict
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wochterbuch-internal


volumes:
  wochterbuch-postgres:

networks:
  wochterbuch-internal:
    driver: bridge
